name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files in repository
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: python manage.py migrate
      working-directory: .
      env:
        DJANGO_SETTINGS_MODULE: url_shortener.settings

    - name: Run Django tests
      run: python manage.py test
      working-directory: .
      env:
        DJANGO_SETTINGS_MODULE: url_shortener.settings/

    - name: Build Docker image
      run: docker build -t url-shortener-django .
