name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django migrations
      run: python manage.py migrate
      working-directory: ./url_shortener

    - name: Run Django tests
      run: python manage.py test
      working-directory: ./url_shortener

    - name: Build Docker image
      run: docker build -t url-shortener-django .
